name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: spider go
      run: |
        python zhpicSpider.py
    
    - name : list file of curdir
      run: ls

    - name: push to this repo
      run: |
        git config --global user.name "Ericam"
        git config --global user.email "850552586@qq.com"
        git add result/ && echo A
        git commit -m 'upload zhihupic result' && echo B
        git push -u origin master && echo C
        
    - name: Failure test
      if: failure()
      run: | 
        ls
        echo 55555  

    
